### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by r-e-d-ant** [Carifika-Canada-Inc/static#5]
Hello Everyone,
I was trying to attach the header on a single-service page, But there is some problems of stylings of it.

So everyone I think we should look forward how to fix it.

Thank you.

[Link to header.css](https://github.com/Carifika-Canada-Inc/static/blob/gabriel-branch/assets/css/custom/header.css)

![Header screenshots](https://user-images.githubusercontent.com/66163130/129487963-3412a366-3132-4908-a9dd-67b986b615b5.png)

**Comment by happiguru** [comment]
The issue has been resolved.

Thank you
